version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - todo-backend/mongo_data:/data/db
  
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - todo-backend/redis_data:/data
  
  todo-backend:
    image: todo-backend
    build:
      context: .
      dockerfile: todo-backend/Dockerfile
    environment:
      - PORT=3003
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - NODE_ENV=production
    container_name: todo-backend
    depends_on:
      - mongo
      - redis

  todo-frontend:
    image: todo-frontend
    build:
      context: .
      dockerfile: todo-frontend/Dockerfile
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=http://nginx:8080/api
    container_name: todo-frontend
    depends_on:
      - todo-backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - todo-backend
      - todo-frontend

volumes:
  mongo_data:
  redis_data: