version: '3.8'

services:
  todo-frontend-dev:
    image: todo-frontend-dev
    build:
      context: .
      dockerfile: todo-frontend/dev.Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app
    #ports:
      #- 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    container_name: todo-frontend-dev
    depends_on:
      - todo-backend-dev
      
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ../todo-backend/mongo_data:/data/db
  
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ../todo-backend/redis_data:/data
  
  todo-backend-dev:
    image: todo-backend-dev
    build:
      context: .
      dockerfile: todo-backend/dev.Dockerfile
    volumes:
      - ./todo-backend/:/usr/src/app
    #ports:
      #- 3003:3003
    environment:
      - PORT=3003
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    container_name: todo-backend-dev
    depends_on:
      - mongo
      - redis
    


  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - todo-frontend-dev
      - todo-backend-dev

volumes:
  mongo_data:
  redis_data: